### ISSUE TITLE
What is the voltage Range of 2 Uf Capacitor?

### ISSUE THREAD

**Issue by rupeshdudakiya** [gavinlyonsrepo/LCR_meter#1]

**Comment by gavinlyonsrepo** [comment]
Hi 

The circuit is limited at 5V vcc so anything above 7 v should be good.
Make sure to use Use  non-polarized .

I used 2 *  1uF 50V Monolithic Ceramic Chip Capacitor in parallel when i tested.

**Comment by kenta2412** [comment]
thank you!

Vào 24-04-2021 7:51, "Gavin Lyons" ***@***.***> đã viết:
